config/routes.rb
Rails.application.routes.draw do

  root 'documents#index'

  resources :documents do
    member do
      get :delete
    end
    collection do
      get :share
      post :save_share
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_many :shared_documents
  has_attached_file :pdf

  validates_attachment_presence :pdf
  validates_attachment :pdf, content_type: { content_type: "application/pdf" }

  scope :visible, lambda { where(:visible => true) }
  scope :invisible, lambda { where(:visible => false) }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :oldest_first, lambda { order("created_at ASC") }
  scope :search_name, lambda {|query| where(["document_name LIKE ?", "%#{query}%"]) }
  scope :search_user, lambda {|query| where(["user_id = ?", "%#{query}%"]) }
end

app/models/shared_document.rb
class SharedDocument < ApplicationRecord
  belongs_to :sender    ,class_name: "User"
  belongs_to :receiver  ,class_name: "User"
  belongs_to :document

  scope :newest_first, lambda { order("created_at DESC") }
  scope :oldest_first, lambda { order("created_at ASC") }
  scope :search_sender, lambda {|query| where(["sender_id = ?", "%#{query}%"]) }
  scope :search_receiver, lambda {|query| where(["receiver_id = ?", "%#{query}%"]) }
  scope :search_document, lambda {|query| where(["document_id = ?", "%#{query}%"]) }
end

app/models/user.rb
class User < ApplicationRecord
  has_one :user_profile
  has_many :documents
  has_many :sender_ids, :class_name => 'SharedFile', :foreign_key => 'sender_id'
  has_many :receiver_ids, :class_name => 'SharedFile', :foreign_key => 'receiver_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user

  scope :search_user, lambda {|query| where(["user_id = ?", "%#{query}%"]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @documents = Document.where(user_id: current_user.id).newest_first
    @by_me = SharedDocument.where(sender_id: current_user.id).newest_first
    @with_me = SharedDocument.where(receiver_id: current_user.id).newest_first
  end

  def show
    @doc = Document.find(params[:id])
    qrcode = RQRCode::QRCode.new( @doc.pdf.url)
    png = qrcode.as_png(
          resize_gte_to: false,
          resize_exactly_to: false,
          fill: 'white',
          color: 'black',
          size: 1024,
          border_modules: 4,
          module_px_size: 6,
          file: nil # path to write
          )
    path = "public/qrcodes/#{@doc.document_name}#{@doc.id}.png"
    png.save(path, :interlace => true)
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    @document.user_id = current_user.id
    if @document.document_name.to_s.empty?
        @document.document_name = @document.pdf_file_name
    end
    if @document.save
      #redirect
      flash[:success] = "PDF uploaded successfully."
      redirect_to(documents_path)
    else
      flash[:error] = "PDF upload failed."
      render('new')
    end
  end

  def document_params
    params.require(:document).permit(:pdf, :document_name)
  end

  # def edit
  # end
  #
  # def update
  # end
  #
  # def delete
  # end
  #
  # def destroy
  # end

  def share
    @other_users = User.where.not(id: current_user.id)
    @my_files = Document.where(user_id: current_user.id)
    @shared_document = SharedDocument.new
  end

  def save_share
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "error"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">x</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/delete.html.erb
<h1>Documents#delete</h1>
<p>Find me in app/views/documents/delete.html.erb</p>

app/views/documents/edit.html.erb
<h1>Documents#edit</h1>
<p>Find me in app/views/documents/edit.html.erb</p>

app/views/documents/index.html.erb
<% @page_title = "All Documents" %>
<%= javascript_include_tag('home.js') %>

<div class="container">
				<div class="row col-xs-12">
					<div class="aligncenter"><h1 class="jumbotron text-left">SmartPDF Home</h1></div>
					<form class="col-xs-12 jumbotron blue">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="panel wnt panel-primary">
								<div class="panel-heading">
									<ul class="nav nav-tabs">
										<li class="active col-xs-4"><a href="#tab1" data-toggle="tab">My Files</a></li>
										<!-- <li class="col-xs-4"><a href="#tab2" data-toggle="tab">Shared By Me</a></li>
										<li class="col-xs-4"><a href="#tab3" data-toggle="tab">Shared With Me</a></li> -->
									</ul>
								</div>
								<div class="container">
									<div class="panel-body">
										<div class="row">
											<div class="col-lg-12">
												<div class="col-md-12">
													<div class="tab-content">
														<div class="tab-pane fade in active" id="tab1">
															<table class="table table-bordered table-hover" id="tab_logic">
																<thead>
																	<tr>
																		<th class="text-left">
																			My Files
																		</th>
																	</tr>
																</thead>
																<tbody data-link="row" class="rowlink">
                                  <% @documents.each do |document| %>
																		<tr><td>
																			<%= link_to(document.document_name, document_path(:id => document.id), :class => 'action show') %>
																		</td></tr>
                                  <% end %>
																</tbody>
															</table>
														</div>
														<!-- <div class="tab-pane fade" id="tab2">
															<table class="table table-bordered table-hover" id="tab_logic">
																<thead>
																	<tr>
																		<th class="text-left">
																			Shared By Me
																		</th>
																	</tr>
																</thead>
																<tbody data-link="row" class="rowlink">
																	<% @by_me.each do |sd| %>
																		<tr><td>
																			<%= link_to(sd.document.document_name, document_path(:id => sd.document.id), :class => 'action show') %>
																		</td></tr>
                                  <% end %>
																</tbody>
															</table>
														</div>
														<div class="tab-pane fade" id="tab3">
															<table class="table table-bordered table-hover" id="tab_logic">
																<thead>
																	<tr>
																		<th class="text-left">
																			Shared With Me
																		</th>
																	</tr>
																</thead>
																<tbody data-link="row" class="rowlink">
																	<% @with_me.each do |sd| %>
																		<tr><td>
																			<%= link_to(sd.document.document_name, document_path(:id => sd.document.id), :class => 'action show') %>
																		</td></tr>
                                  <% end %>
																</tbody>
															</table>
														</div> -->
													</div>
												</div>
											</div>
										</div>
									</div>

								</div>
								<div class="panel-footer">
									<button type="button" class="btn btn-link"><%= link_to("Upload File", new_document_path, :class => 'action new') %></button>
									<button type="button" class="btn btn-link pull-right"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></button>
								</div>
							</div>
						</div>

				</div>
					</form>
				</div>
</div>

app/views/documents/new.html.erb
<div class="container">
				<div class="row col-xs-12">
					<div class="aligncenter"><h1 class="jumbotron text-left">SmartPDF Upload</h1></div>
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h3 class="panel-title">Upload File</h3>
								</div>

								<div class="container">
									<div class="form-group">
                  </br>
                        <%= form_for @document, url: documents_path, html: { multipart: true } do |form| %>
                        <h5>Document Name</h5>
                          <%= form.text_field :document_name %>
                          </br></br>
                          <%= form.file_field :pdf %>
                          </br>
                          <%= form.submit "Upload", :class => "btn btn-primary"%>
                        <% end %>
									</div class="form-group">
								</div>

								<div class="panel-footer">
									<button type="button" class="btn btn-link"><%= link_to("Home", documents_path) %></button>
									<button type="button" class="btn btn-link pull-right"><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </button>
								</div>
						</div>
				</div>
</div>

app/views/documents/share.html.erb
<div class="container">
				<div class="row col-xs-12">
					<div class="aligncenter"><h1 class="jumbotron text-left">SmartPDF Share</h1></div>
					<form class="col-xs-12 jumbotron blue">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h3 class="panel-title">Share File</h3>
								</div>

								<div class="container">
									<div class="form-group">
										<div class="panel-body">

													<ul class="list-group">
														<h4 class="list-group-item-heading">Files</h4>
														<li  class="list-group-item active">File_1.pdf</li>
														<li class="list-group-item">File_2.pdf</li>
														<li class="list-group-item">File_3.pdf</li>
														<li class="list-group-item">File_4.pdf</li>
													</ul>

													<ul class="list-group">
														<h4 class="list-group-item-heading">Users</h4>
														<li  class="list-group-item active">User 1</li>
														<li class="list-group-item">User 2</li>
														<li class="list-group-item">User 3</li>
														<li class="list-group-item">User 4</li>
													</ul>

											<button type="submit" class="btn btn-primary">Share</button>
										</div>
									</div class="form-group">
								</div>

								<div class="panel-footer">
									<button type="button" class="btn btn-link">Home</button>
									<button type="button" class="btn btn-link pull-right">Log out</button>
								</div>
						</div>
					</form>
				</div>
</div>

app/views/documents/show.html.erb
<div class="container">
				<div class="row col-xs-12">
					<div class="aligncenter"><h1 class="jumbotron text-left">SmartPDF File</h1></div>
					<form class="col-xs-12 jumbotron blue">
						<div class="col-xs-12 col-sm-12 col-md-12">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h3 class="panel-title">File information</h3>
								</div>

								<div class="container">
									<div class="form-group">
										<div class="panel-body">
											<pre><%= @doc.document_name%></pre>

											<div class="form-group">
												<%= image_tag("/qrcodes/#{@doc.document_name}#{@doc.id}.png", :class => 'img-thumbnail', :alt => 'QR Code Not Found')%>
												<!--img src= "" alt="QR Code Not Found" class="img-thumbnail"-->
											</div>

											<!-- <button type="submit" class="btn btn-primary">Share</button> -->
										</div>
									</div class="form-group">
								</div>

								<div class="panel-footer">
									<button type="button" class="btn btn-link"><%= link_to 'Home', url_for(:back) %></button>
									<button type="button" class="btn btn-link pull-right"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></button>
								</div>
						</div>
					</form>
				</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>